config/routes.rb
Rails.application.routes.draw do
  get 'introduction/index'

  get 'introduction/farmer1'

  get 'introduction/farmer2'

  get 'introduction/farmer3'

  get 'introduction/farmer4'

  devise_for :users
  resources :organics

  resource :cart, only: [:show, :destroy] do
    collection do
      post :add,path: 'add/:id'
    end
  end

  root "organics#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
     
end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(organic_id)
    found_item = items.find { |item| item.organic_id == organic_id }

    if found_item
      found_item.increment
    else
      @items << CartItem.new(organic_id)
    end
  end

  def empty?
    items.empty?
  end

  def total_price
    items.reduce(0) { |sum, item| sum + item.price }
  end

  def serialize
    all_items = items.map { |item|
      { "organic_id" => item.organic_id, "quantity" => item.quantity}
    }

    { "items" => all_items }
  end

  def self.from_hash(hash)
    if hash.nil?
      new []
    else
      new hash["items"].map { |item_hash|
        CartItem.new(item_hash["organic_id"], item_hash["quantity"])
      }
    end
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :organic_id, :quantity

  def initialize(organic_id, quantity = 1)
    @organic_id = organic_id
    @quantity = quantity
  end

  def increment(n = 1)
    @quantity += n
  end

  def organic
    Organic.find_by(id: organic_id)
  end

  def price
    organic.price * quantity
  end
end

app/models/organic.rb
class Organic < ApplicationRecord
  validates :title, presence: true
	belongs_to :owner, class_name: "User", foreign_key: :user_id
#   has_attached_file :image, styles: { :medium => "400x400#" }
# 	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	
	mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :organics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
   #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

    include CartsHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add
    current_cart.add_item(params[:id])

    session[:cart9487] = current_cart.serialize
    redirect_to organics_path, notice: "add to cart!"
  end

  def destroy
    session[:cart9487] = nil
    redirect_to organics_path, notice: "empty to cart!"
  end
end

app/controllers/introduction_controller.rb
class IntroductionController < ApplicationController
  def index
  end

  def farmer1
  end

  def farmer2
  end

  def farmer3
  end

  def farmer4
  end
end

app/controllers/organics_controller.rb
class OrganicsController < ApplicationController

  before_action :find_by, only:[:show, :edit, :update, :destroy]


  def index
    @organics = Organic.all
  end

  def new
    @organic = Organic.new
  end

  def edit
  end

  def update
   if @organic.update(organic_params)
     redirect_to organics_path, notice: "Organic was updated successfully"
   else
   render "edit"
   end
  end

  def destroy
    @organic.destroy
    redirect_to organics_path, notice: "Organic was delete!!"
  end

  def show
  end

   def create
    @organic = current_user.organics.new(organic_params)

     if @organic.save
    #flash[:notice] = "Candidate was created successfully"
    redirect_to organics_path, notice: "Organic was created successfully"

    else
    render "new"
    end
  end

end

private
  def organic_params
    params.require(:organic).permit(:title, :description, :price, :image)
  end

  def find_by
     @organic = Organic.find_by(id: params[:id])
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    @cart ||= Cart.from_hash(session[:cart9487])
  end
end

app/helpers/introduction_helper.rb
module IntroductionHelper
end

app/helpers/organics_helper.rb
module OrganicsHelper
  def isAdmin?(email)
    email.eql? "chi19961202@gmail.com"      
  end
end

app/views/carts/show.html.erb
<h1>購物車</h1>
<div style="float:right">
  <%= link_to "清空購物車", cart_path, method: "delete",class: "btn btn-danger" %>
</div><br/><br/>

<div style="text-align:center">
  <table class="table table-hover">
    <col class="col1" width="20%">
  	<col class="col1" width="20%">
  	<col class="col1" width="20%">
  	<col class="col1" width="20%">
  	<col class="col1" width="20%">
    <thead>
      <tr class="success">
        <td><h4>商品圖片</h4></td>
        <td><h4>商品名稱</h4></td>
        <td><h4>數量</h4></td>
        <td><h4>單價</h4></td>
        <td><h4>小計</h4></td>
      </tr>
    </thead>
    <tbody>
      <% current_cart.items.each do |item| %>
        <tr>
          <td><%= image_tag(item.organic.image_url, :width => '150px', :height => '150px') %></td>
          <td><%= item.organic.title %></td>
          <td><%= item.quantity %></td>
          <td><%= item.organic.price %></td>
          <td><%= item.price %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
    <tr class="danger">
      <td><h4>總計</h4></td>
      <td></td>
      <td></td>
      <td></td>
      <td><h4><%= current_cart.total_price %></h4></td>
    </tfoot>
  </table>
</div>

  <%= link_to '繼續選購', organics_path, class: "btn btn-default" %>
  <%= link_to '結帳', '#', class: "btn btn-default" %>

app/views/introduction/farmer1.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Row -->
      <div class="row">
        <div class="col-md-4">
          <%= image_tag("farmer1.jpg", height: 300, width: 300, :class => "img-circle" ) %>
        </div>
        <div class="col-md-8">
          <span style="font-family:Microsoft JhengHei;">
          <h2 class="my-3"><b>語林有機農場</b></h2></br>
          <h4 class="text-success">健康追求者，種下林口的有機夢</h4></br>
          <h4>邱語玲與林元郁夫婦倆，在職場看盡人情冷暖，拖著疲憊且不健康的身子，回
到林口幫公公一起守護田地。兩個第一次種田的人，雖然一切都需重頭學起，
但看到這些有機蔬果們長得頭好壯壯，工作雞在田裡奔跑吃蟲，換來簡單且快
樂的生活，夫復何求？在熟悉有機農業後，也不吝分享經驗，除了到社區大學
授課，更成立林口台地農夫市集，搭起在地有機小農與消費者間的橋梁。林口
的有機夢，就從這裡開始…。</h4></span>
        </div>
        <div class="row">
          <div style="margin-top: 350px;">
          <div align="right">
          <%= image_tag("footer_1.jpg", height: 150, width: 800) %>
          </div>
        </div>
        </div>
      </div>
      <!-- /.row -->
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <!-- <script src="jquery/jquery.min.js"></script> -->
    <!-- <script src="jquery/bootstrap.bundle.min.js"></script> -->
  </body>
</html>

app/views/introduction/farmer2.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Row -->
      <div class="row">
        <div class="col-md-4">
          <%= image_tag("farmer2.jpg", height: 300, width: 300, :class => "img-circle" ) %>
        </div>
        <div class="col-md-8">
          <span style="font-family:Microsoft JhengHei;">
          <h2 class="my-3"><b>芽寶寶有機農場</b></h2><br>
          <h4 class="text-success">堅強女子力，專利技術栽培的無介質活芽菜</h4><br>
          <h4>看似簡單的芽菜培養工作，隱藏著重重難關，劉金枝不斷嘗試各種芽菜的種植
方式與銷售組合，經過多年努力，屬於她的芽菜小王國已然成形。芽寶寶的無塵
培芽室採用恆溫、過濾、自動灑水系統，確保生產過程汙染風險降到最低，有
機種子經獨家專利無介質栽培技術播種，出貨時的芽菜仍維持著成長中的狀態
，保鮮期更長。芽寶寶的11種活芽菜，全經有機驗證，纖維高、維生素多、且充
滿酵素。洗後直接生吃，口齒間迸發的濃郁及營養，清甜響脆，就如同芽寶寶
的初衷，簡單而純粹。</h4></span>
        </div>
        <div class="row">
          <div style="margin-top: 350px;">
          <div align="right">
          <%= image_tag("footer_2.jpg", height: 150, width: 800) %>
          </div>
        </div>
        </div>
      </div>
      <!-- /.row -->
    <!-- /.container -->

  </body>
</html>

app/views/introduction/farmer3.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Row -->
      <div class="row">
        <div class="col-md-4">
          <%= image_tag("farmer3.jpg", height: 300, width: 300, :class => "img-circle" ) %>
        </div>
        <div class="col-md-8">
          <span style="font-family:Microsoft JhengHei;">
          <h2 class="my-3"><b>周好小有機農場</b></h2><br>
          <h4 class="text-success">為家人種菜，讓家人好好吃飯，足好</h4><br>
          <h4>周好小農場，台語發音為「足好」，農場主人周業鑑從小在林口長大，在辭去
證券公司的工作後，回到哺育他的這塊土地，抱持為家人種出安心蔬菜的理念
，開始了有機栽培人生。回首草創時期，從慣行農法轉作有機的過程中，第一
年的收成連自己吃都不夠，經由語林農場的帶領、以及自己努力鑽研，利用生
物防治，搭配順應時節耕種適合的作物，產量漸趨穩定。現在，周業鑑要將周好
小農場的青花筍、絲瓜、西瓜…等有機蔬果，以及他為家人著想的心，一同分
享給大家。</h4></span>
        </div>
        <div class="row">
          <div style="margin-top: 350px;">
          <div align="right">
          <%= image_tag("footer_3.jpg", height: 150, width: 800) %>
          </div>
        </div>
        </div>
      </div>
      <!-- /.row -->
    <!-- /.container -->

  </body>
</html>

app/views/introduction/farmer4.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Row -->
      <div class="row">
        <div class="col-md-4">
          <%= image_tag("farmer4.jpg", height: 300, width: 300, :class => "img-circle" ) %>
        </div>
        <div class="col-md-8">
          <span style="font-family:Microsoft JhengHei;">
          <h2 class="my-3"><b>畦遊季有機農場</b></h2><br>
          <h4 class="text-success">三個年輕人，一起返鄉種菜、大話畦遊</h4><br>
          <h4>原先在同家公司上班的謝祥文、張文棟、陳坤峯三個七年級生，由於看中了有
機產業的前景及友善農耕的永續性，因此決定一起返鄉合夥創業。分別就讀病
蟲害、建築工程、園藝的三人，就像西遊記裡的師兄弟一樣，各司其職，一同
面對農場經營的大小困難。透過科技化數據和前輩的協助，生產各式短期有機
葉菜，加上以工換菜、學校食農教育、社區大學授課等活動及社群行銷，帶領更
多人認識農業與在地生態。未來，他們將會繼續在林口的小山谷中扎根，守護
這片土地。</h4></span>
        </div>

        <div class="row">
          <div style="margin-top: 350px;">
          <div align="right">
          <%= image_tag("footer_4.jpg", height: 150, width: 800) %>
          </div>
        </div>
        </div>
      </div>
      <!-- /.row -->
    <!-- /.container -->

  </body>
</html>

app/views/introduction/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>

  <body>
    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Row -->
      <div class="row">
        <div class="col-md-4">
        <br><%= image_tag("introduction.jpg", height: 250, width: 350) %>
        </div>
        <div class="col-md-8">
          <span style="font-family:Microsoft JhengHei;">
          <h2 class="my-3"></h2><br>
          <h3 class="text-success">關於有機這條艱苦又幸福的路</h3><br>
          <h4>林口有機小農由四家具有相同理念的林口在地農場所組成----<br>語林有機農場、芽寶寶有機農場、周好小有機農場、畦遊季有機農場。<br>我們在從事有機的路上，曾經跌跌撞撞，但彼此之間的幫助與扶持，讓這條路不再難行。<br>如今，我們組成林口有機聯盟一年365天，提供多元的當季有機蔬菜、根莖、瓜果、芽菜。<br>我們喜愛我們的家鄉，我們珍惜我們的家人朋友，提供健康安心的蔬果，是我們表達愛的方式<br>和我們一起友善環境、永續經營，為我們所愛的人，奉上一盤來自林口的有機美味。</h4></span>
        </div>

        <div class="row">
          <div style="margin-top: 350px;">
          <div align="center">
          <%= image_tag("introduction0.jpg", height: 150, width: 1100) %>
          </div>
        </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div style="margin-top: 25px;">
            <div style="border-left: 2px solid #000; margin-bottom: 10px;">
                <h5 style="padding-left: 10px; font-family:Microsoft JhengHei;"><b>回到自己家鄉耕種是一種享受<b><br>
                <b>從一開始一片毫無生機的土地，經過大家一番努力，翻土、播種、種植、採收這些繁雜的步驟，慢慢的點綴整個土地，農作物逐漸成長茁壯，像孩子般的成長，與我們培養出無限的感情<br>為了就是讓大家能夠吃到健康安心的食物。<b></h5>
            </div>
          </div>
        </div>
        </div>
      </div>
      <!-- /.row -->
    <!-- /.container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oragnic Product</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <span style="font-family:Microsoft JhengHei;">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Organic Product", organics_path, :class=>'navbar-brand'%>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "有機農產介紹" , introduction_index_path %></li>
          <li><%= link_to "語林有機農場" , introduction_farmer1_path %></li>
          <li><%= link_to "芽寶寶有機農場" , introduction_farmer2_path %></li>
          <li><%= link_to "周好小有機農場" , introduction_farmer3_path %></li>
          <li><%= link_to "畦遊季有機農場" , introduction_farmer4_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !current_user %>
            <li> <%= link_to " Sign up", new_user_registration_path, :class=>"glyphicon glyphicon-user" %> </li>
            <li> <%= link_to " Login", new_user_session_path, :class=>"glyphicon glyphicon-log-in" %> </li>
          <% else %>
            <li> <%= link_to current_user.name, edit_user_registration_path, :class=>"glyphicon glyphicon-user" %></li>
            <li> <%= link_to " Setting", edit_user_registration_path, :class=>"glyphicon glyphicon-cog" %></li>
          <% end %>
          <li> <%= link_to " Logout", destroy_user_session_path, method: "delete", :class=>"glyphicon glyphicon-log-out" %> </li>
          <li><%= link_to " Shopping Cart", cart_path, :class=>"glyphicon glyphicon-shopping-cart" %></li>
        </ul>
      </div>
    </nav>


    <div class="container">
      <% if flash[:notice] %>
          <div class ="alert alert-info" role="alert"><%= flash[:notice] %></div>
        <% end %>
      <%= yield %>
    </div>
    </span>
  </body>
</html>

app/views/organics/_form.html.erb
<%= simple_form_for organic, html: { multipart: true } do |f| %>
  <%= f.input :title %><br />
  <%= f.input :description %><br />
  <%= f.input :price %><br />
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/organics/edit.html.erb
<%= flash[:notice] %>
<h1>
  edit organic
</h1>
 <%= render "form" ,organic: @organic %>

app/views/organics/index.html.erb
<div class="container">
  
  <div class="row" id="cus">
    <div class="col-xs-9">
      <div class="row">
        <div class="col-xs-12">
<!--    //////////////                      輪播    ///////////////////                                                  -->
					<div class="container-fluid">
						<div class="row">
							<div class="col-md-12">
								<div class="carousel slide" id="carousel-819398">
									<ol class="carousel-indicators">
										<li class="active" data-slide-to="0" data-target="#carousel-819398">
										</li>
										<li data-slide-to="1" data-target="#carousel-819398">
										</li>
										<li data-slide-to="2" data-target="#carousel-819398">
										</li>
									</ol>
									<div class="carousel-inner">
										<div class="item active">
											<%= image_tag("slide1.jpg") %>
										</div>
										<div class="item">
											<%= image_tag("slide2.jpg") %>
										</div>
										<div class="item">
											<%= image_tag("slide3.jpg") %>
										</div>
									</div> <a class="left carousel-control" href="#carousel-819398" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-819398" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
								</div>
							</div>
						</div>
					</div>

<!--    //////////////                      輪播    ///////////////////                                                  -->
        </div>
      </div>
			<div style="margin-top: 30px;">
      <div class="row">
        <% @organics.each do |organic| %>
          <div class="col-xs-4">
            <div class="thumbnail">
             <td><%= link_to image_tag(organic.image_url, :width => '90%', :height => '30px'), organic if organic.image.present?%></td>
              <div class="caption">
                <h3><%= link_to organic.title, organic_path(organic) %></h3>
                <p><%= organic.description %></p>
                <p>
									<% if user_signed_in? %>
    								<% if isAdmin?(current_user.email) %>
											<%= link_to "edit" , edit_organic_path(organic) , class: "btn btn-success" %>
											<%= link_to "delete" , organic_path(organic), method: "delete" , data: {confirm: "Are you sure?!"} %>
										<% end %>
 									<% end %>
									<%= link_to '加入購物車', add_cart_path(organic), method: "post", class: "btn btn-xs btn-danger" %>
								</p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
	  </div>
    </div>
  </div>
</div>

  <% if user_signed_in? %>
		<% if isAdmin?(current_user.email) %>
			<%= link_to "add organic", new_organic_path , class: "btn btn-danger" %>
		<% end %>
	<% end %>

app/views/organics/new.html.erb
<h1>
  add organic
</h1>

 <%= render "form", organic: @organic %>

app/views/organics/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap 3, from LayoutIt!</title>

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="LayoutIt!">

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

  </head>
  <body>

    <div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="row">
						<div style="margin-top: 20px;">
							<div class="col-md-6">
								<%= image_tag(@organic.image_url, :width => 450, :class => "img-thumbnail") if @organic.image.present? %>
							</div>
						</div>
						<div class="col-md-6">
							<h2 class="text-primary">
								<b><%= @organic.title %></b>
							</h2>
							  <br />
								<h4>
									<%= @organic.description %>
								</h4>
								<br />
								<h4>
								價格 : <%= @organic.price %>
							  </h4>
							<p>
								<br />
								<%= link_to "加入購物車", add_cart_path, method: "post", class: "btn btn-danger" %>
							</p>
						</div>
					</div><br />
					<div class="tabbable" id="tabs-86935">
						<ul class="nav nav-tabs">
							<li>
								<a href="#panel-943359" data-toggle="tab">商品介紹</a>
							</li>
							<li class="active">
								<a href="#panel-443052" data-toggle="tab">配送須知</a>
							</li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane" id="panel-943359">
								<br />
								<h4 class="text-success"><b>健康追求者，種下林口的有機夢</b></h4></br>
								<div align="center">
									<%= image_tag("簡介1.jpg", height: 1300, width: 1100 ) %>
								</div>
							</div>
							<div class="tab-pane active" id="panel-443052">
								<div class="row">
									<div class="col-md-12"><br />
										<ul>
											<li>
												宅配到府
											</li>
											<li>
												配送地點僅侷限於北部地區
											</li>
											<li>
												配送時間:上午8:00~下午5:00
											</li>
											<li>
												貨到付款
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/scripts.js"></script>
  </body>
</html>